services:
  frontend:
    build:
      context: frontend
      # target: development
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - mern-stripe-app
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: backend
      # target: development
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    # depends_on:
    #   - mongo
    networks:
      - mern-stripe-app
      # - express-mongo
    expose:
      - 8000
  # mongo:
  #   restart: always
  #   image: mongo:4.2.0
  #   volumes:
  #     - ./data:/data/db
  #   networks:
  #     - express-mongo
  #   expose:
  #     - 27017
networks:
  mern-stripe-app:
  # express-mongo:
