const validationTypes = {
  VALIDATOR_TYPE_REQUIRE: 'REQUIRE',
  VALIDATOR_TYPE_MINLENGTH: 'MINLENGTH',
  VALIDATOR_TYPE_MAXLENGTH: 'MAXLENGTH',
  VALIDATOR_TYPE_MIN: 'MIN',
  VALIDATOR_TYPE_MAX: 'MAX',
  VALIDATOR_TYPE_EMAIL: 'EMAIL',
  VALIDATOR_TYPE_FILE: 'FILE',
};

export default validationTypes;
